# Generated by Django 2.1.5 on 2019-01-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0002_auto_20190130_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_agent',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
